[build]
target = "thumbv6m-none-eabi"

[env]
DEFMT_LOG = "info"

[target.thumbv6m-none-eabi]
runner = "probe-rs run --chip RP2040 --probe 2e8a:000c"
rustflags = [
  "-C", "link-arg=--nmagic",
]

[alias]
fw-build-usb = "build --no-default-features --features usb-bridge"
fw-run-usb = "run --no-default-features --features usb-bridge"
fw-build-pio = "build --no-default-features --features pio-real"
fw-run-usb-defmt = "run --no-default-features --features usb-bridge,defmt-log"
