[build]
target = "thumbv6m-none-eabi"

[env]
DEFMT_LOG = "info"

[target.thumbv6m-none-eabi]
runner = "probe-rs run --chip RP2040 --probe 2e8a:000c"
rustflags = [
  "-C", "link-arg=--nmagic",
]

[alias]
fw-build = "build"
fw-run = "run"
fw-build-pio = "build --no-default-features --features pio-real,defmt-log"
fw-run-pio = "run --no-default-features --features pio-real,defmt-log"
