[package]
name = "rp2040-fred-firmware"
version = "0.1.0"
edition = "2021"

[features]
default = ["mock-bus"]
mock-bus = []
pio-real = []

[dependencies]

[target.'cfg(target_arch = "arm")'.dependencies]
portable-atomic = { version = "1", features = ["critical-section"] }
panic-halt = "0.2"
cortex-m-rt = "0.7"
embassy-executor = { version = "0.7", features = ["arch-cortex-m", "executor-thread"] }
embassy-time = { version = "0.3", features = ["tick-hz-1_000_000"] }
embassy-rp = { version = "0.2", features = ["critical-section-impl", "time-driver"] }
pio = "0.2"
pio-proc = "0.2"
rp-pac = "6"

[profile.dev]
opt-level = 1
debug = 2
codegen-units = 1
lto = false

[profile.release]
opt-level = 3
debug = 1
codegen-units = 1
lto = true
